### ISSUE TITLE
Couldn't git clone https://github.com/tarikogut/JasminWebPanel

### ISSUE THREAD

**Issue by darrylsepeda** [samael33/jasmin-gui-docker#1]
Seems the other repo already been deleted by the owner,
may I know what's inside that repo?
or how can I run jasmin gui in docker without that repo?
thanks in advance!

**Comment by igorolhovskiy** [comment]
Hi!
Just found alternative fork https://github.com/amelyec/JasminWebPanel or https://github.com/101t/jasmin-web-panel
Choose the one you like, I'm not working with this technology anymore, so don't really support it.

**Comment by darrylsepeda** [comment]
thanks for your reply, it works using `amelyec` but not working with the `101t`.
btw, when I open the GUI, it shows login page, but I couldn't find any clue about the username and password, do you know where can I set or find about this info?

I really appreciate your help knowing you don't work in this project anymore.
thank you @igorolhovskiy

**Comment by igorolhovskiy** [comment]
I think some default values. Like admin:admin. But have no idea tbh

**Comment by darrylsepeda** [comment]
it doesn't work with admin:admin, but i'll try to search again tonight.
Thank you for your help!
